/*
 * NiFi Rest Api
 * The Rest Api provides programmatic access to command and control a NiFi instance in real time. Start and                                              stop processors, monitor queues, query provenance data, and more. Each endpoint below includes a description,                                             definitions of the expected input and output, potential response codes, and the authorizations required                                             to invoke each service.
 *
 * OpenAPI spec version: 1.13.0
 * Contact: dev@nifi.apache.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.AffectedComponentEntity;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * ParameterDTO
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-03-11T15:06:11.268+01:00")
public class ParameterDTO {
  @SerializedName("name")
  private String name = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("sensitive")
  private Boolean sensitive = null;

  @SerializedName("value")
  private String value = null;

  @SerializedName("valueRemoved")
  private Boolean valueRemoved = null;

  @SerializedName("referencingComponents")
  private List<AffectedComponentEntity> referencingComponents = null;

  public ParameterDTO name(String name) {
    this.name = name;
    return this;
  }

   /**
   * The name of the Parameter
   * @return name
  **/
  @ApiModelProperty(value = "The name of the Parameter")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public ParameterDTO description(String description) {
    this.description = description;
    return this;
  }

   /**
   * The description of the Parameter
   * @return description
  **/
  @ApiModelProperty(value = "The description of the Parameter")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public ParameterDTO sensitive(Boolean sensitive) {
    this.sensitive = sensitive;
    return this;
  }

   /**
   * Whether or not the Parameter is sensitive
   * @return sensitive
  **/
  @ApiModelProperty(value = "Whether or not the Parameter is sensitive")
  public Boolean isSensitive() {
    return sensitive;
  }

  public void setSensitive(Boolean sensitive) {
    this.sensitive = sensitive;
  }

  public ParameterDTO value(String value) {
    this.value = value;
    return this;
  }

   /**
   * The value of the Parameter
   * @return value
  **/
  @ApiModelProperty(value = "The value of the Parameter")
  public String getValue() {
    return value;
  }

  public void setValue(String value) {
    this.value = value;
  }

  public ParameterDTO valueRemoved(Boolean valueRemoved) {
    this.valueRemoved = valueRemoved;
    return this;
  }

   /**
   * Whether or not the value of the Parameter was removed. When a request is made to change a parameter, the value may be null. The absence of the value may be used either to indicate that the value is not to be changed, or that the value is to be set to null (i.e., removed). This denotes which of the two scenarios is being encountered.
   * @return valueRemoved
  **/
  @ApiModelProperty(value = "Whether or not the value of the Parameter was removed. When a request is made to change a parameter, the value may be null. The absence of the value may be used either to indicate that the value is not to be changed, or that the value is to be set to null (i.e., removed). This denotes which of the two scenarios is being encountered.")
  public Boolean isValueRemoved() {
    return valueRemoved;
  }

  public void setValueRemoved(Boolean valueRemoved) {
    this.valueRemoved = valueRemoved;
  }

  public ParameterDTO referencingComponents(List<AffectedComponentEntity> referencingComponents) {
    this.referencingComponents = referencingComponents;
    return this;
  }

  public ParameterDTO addReferencingComponentsItem(AffectedComponentEntity referencingComponentsItem) {
    if (this.referencingComponents == null) {
      this.referencingComponents = new ArrayList<AffectedComponentEntity>();
    }
    this.referencingComponents.add(referencingComponentsItem);
    return this;
  }

   /**
   * The set of all components in the flow that are referencing this Parameter
   * @return referencingComponents
  **/
  @ApiModelProperty(value = "The set of all components in the flow that are referencing this Parameter")
  public List<AffectedComponentEntity> getReferencingComponents() {
    return referencingComponents;
  }

  public void setReferencingComponents(List<AffectedComponentEntity> referencingComponents) {
    this.referencingComponents = referencingComponents;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ParameterDTO parameterDTO = (ParameterDTO) o;
    return Objects.equals(this.name, parameterDTO.name) &&
        Objects.equals(this.description, parameterDTO.description) &&
        Objects.equals(this.sensitive, parameterDTO.sensitive) &&
        Objects.equals(this.value, parameterDTO.value) &&
        Objects.equals(this.valueRemoved, parameterDTO.valueRemoved) &&
        Objects.equals(this.referencingComponents, parameterDTO.referencingComponents);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, description, sensitive, value, valueRemoved, referencingComponents);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ParameterDTO {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    sensitive: ").append(toIndentedString(sensitive)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("    valueRemoved: ").append(toIndentedString(valueRemoved)).append("\n");
    sb.append("    referencingComponents: ").append(toIndentedString(referencingComponents)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

