/*
 * NiFi Rest Api
 * The Rest Api provides programmatic access to command and control a NiFi instance in real time. Start and                                              stop processors, monitor queues, query provenance data, and more. Each endpoint below includes a description,                                             definitions of the expected input and output, potential response codes, and the authorizations required                                             to invoke each service.
 *
 * OpenAPI spec version: 1.13.0
 * Contact: dev@nifi.apache.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.VersionedParameter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * VersionedParameterContext
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-03-11T15:06:11.268+01:00")
public class VersionedParameterContext {
  @SerializedName("name")
  private String name = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("parameters")
  private List<VersionedParameter> parameters = null;

  public VersionedParameterContext name(String name) {
    this.name = name;
    return this;
  }

   /**
   * The name of the context
   * @return name
  **/
  @ApiModelProperty(value = "The name of the context")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public VersionedParameterContext description(String description) {
    this.description = description;
    return this;
  }

   /**
   * The description of the parameter context
   * @return description
  **/
  @ApiModelProperty(value = "The description of the parameter context")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public VersionedParameterContext parameters(List<VersionedParameter> parameters) {
    this.parameters = parameters;
    return this;
  }

  public VersionedParameterContext addParametersItem(VersionedParameter parametersItem) {
    if (this.parameters == null) {
      this.parameters = new ArrayList<VersionedParameter>();
    }
    this.parameters.add(parametersItem);
    return this;
  }

   /**
   * The parameters in the context
   * @return parameters
  **/
  @ApiModelProperty(value = "The parameters in the context")
  public List<VersionedParameter> getParameters() {
    return parameters;
  }

  public void setParameters(List<VersionedParameter> parameters) {
    this.parameters = parameters;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VersionedParameterContext versionedParameterContext = (VersionedParameterContext) o;
    return Objects.equals(this.name, versionedParameterContext.name) &&
        Objects.equals(this.description, versionedParameterContext.description) &&
        Objects.equals(this.parameters, versionedParameterContext.parameters);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, description, parameters);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VersionedParameterContext {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    parameters: ").append(toIndentedString(parameters)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

